version: '3.8'

services:
  user-service:
    build:
      context: ./Microservices/user-service
    ports:
      - "3000:3000"
    networks:
      - backend

  product-service:
    build:
      context: ./Microservices/product-service
    ports:
      - "3001:3001"
    networks:
      - backend

  gateway-service:
    build:
      context: ./Microservices/gateway-service
    ports:
      - "3003:3003"
    networks:
      - backend
    depends_on:
      - user-service
      - product-service

networks:
  backend:
    driver: bridge
