version: '3.8'

services:
  user-service:
    build:
      context: ./Microservices/user-service
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge